apiVersion: extensions.diolkos.io/v1
kind: StreamApp
metadata:
  name: time-source
  type: source
spec:
  image: springcloudstream/time-source-rabbit:1.2.0.RELEASE
  app-properties:
  - name: trigger.cron
    type: string
  - name: trigger.date-format
    type: string
  - name: trigger.fixed-delay
    type: int
    default: 1
  - name: trigger.initial-delay
    type: int
    default: 0
  - name: trigger.max-messages
    type: int
    default: 1
  - name: trigger.time-unit
    type: enum
    values: ['NANOSECONDS', 'MICROSECONDS', 'MILLISECONDS', 'SECONDS', 'MINUTES', 'HOURS', 'DAYS']
